# Generated by Django 6.0 on 2026-02-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
