# Generated by Django 6.0 on 2026-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_age'),
        ('pregnancies', '0002_alter_pregnancy_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='hypertension_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='multiple_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['expected_delivery_date'], name='pregnancies_expecte_3f4650_idx'),
        ),
    ]
