# Generated by Django 6.0 on 2026-02-24 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancies', '0003_pregnancy_hypertension_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancies_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
