# Generated by Django 6.0 on 2026-02-12 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_mode', models.CharField(db_index=True, max_length=50)),
                ('birth_weight_g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(7000)])),
                ('place_of_delivery', models.CharField(db_index=True, max_length=100)),
                ('skilled_birth_attendant', models.BooleanField()),
                ('newborn_gender', models.CharField(max_length=10)),
                ('apgar_score_1min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_score_5min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('complications', models.TextField(blank=True, null=True)),
                ('interventions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
