# Generated by Django 6.0 on 2026-02-19 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
        ('patients', '0003_remove_patient_age'),
        ('pregnancies', '0003_pregnancy_hypertension_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='congenital_anomalies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='neonatal_complications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_mode',
            field=models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarean', 'Cesarean'), ('assisted', 'Assisted')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_date'], name='deliveries__deliver_42d0e6_idx'),
        ),
    ]
