# Generated by Django 6.0 on 2026-02-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_alive_delivery_congenital_anomalies_and_more'),
        ('patients', '0003_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
