# Generated by Django 6.0 on 2026-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('medical_record_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(max_length=15)),
                ('national_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('educational_level', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('gravidity', models.PositiveSmallIntegerField(default=0)),
                ('parity', models.PositiveSmallIntegerField(default=0)),
                ('communication_language', models.CharField(max_length=30)),
            ],
        ),
    ]
