# Generated by Django 6.0 on 2026-02-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
