# Generated by Django 6.0 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
