# Generated by Django 6.0 on 2026-02-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '000X_fix_visit_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralVisit',
            fields=[
            ],
            options={
                'verbose_name': 'General Visit',
                'verbose_name_plural': 'General Visits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visits.visit',),
        ),
        migrations.CreateModel(
            name='PostnatalVisit',
            fields=[
            ],
            options={
                'verbose_name': 'Postnatal Visit',
                'verbose_name_plural': 'Postnatal Visits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visits.visit',),
        ),
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
            ],
            options={
                'verbose_name': 'Prenatal Visit',
                'verbose_name_plural': 'Prenatal Visits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visits.visit',),
        ),
    ]
