# Generated by Django 6.0 on 2026-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visit_hemoglobin_level_alter_visit_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('ANC', 'Antenatal Care'), ('PNC', 'Postnatal Care')], db_index=True, max_length=100),
        ),
    ]
